@startuml


' ==== Enums ====
enum BikeType {
    trekking
    electric
}

enum ExperienceLevel {
  beginner
  occasional
  regular
}

enum Level {
  easy
  moderate
  challenging
}

enum destinationType {
  city
  historical
  coastal
  mountainous
}

enum BookingStatus {
  pending
  confirmed
  cancelled
  completed
}


' ==== Main classes ====

class Client {
  +clientId : String
  +firstName : String
  +lastName : String
  +email : String
  +phone : String
  +countryOfResidence : String
  +experienceLevel : ExperienceLevel
}

class Guide {
  +guideId : String
  +Name : String
  +experienceYears : Integer
  +phone : String
  +email : String
}

class TourPackage {
  +tourId : String
  +title : String
  +shortDescription : String
  +durationDays : Integer
  +difficulty : Level
  +currency : String
  +startDate : Date
  +endDate : Date
  +bikeTypeIncluded : 
  +luggageTransport : Boolean

}

class Stage {
  +stageId : String
  +dayNumber : Integer
  +title : String
  +description : String
  +activities : String
  +events : String
  +includedDestinations : String
  +includedCyclingPaths : String
  +guideId : String
  +tourId : String
}

class Destination {
  +destinationId : String
  +name : String
  +country : String
  +region : String
  +type : destinationType
  +latitude : Decimal
  +longitude : Decimal
  +proposedActivities : String
  +notableEvents : String
  +availableHotels : String
}

class CyclingPath {
  +pathId : String
  +name : String
  +difficulty : Level
  +distanceKm : Decimal
  +elevationGainM : Decimal
}

class RentalBike {
  +bikeId : String
  +bikeType : BikeType
  +available  : Boolean
  +rentalPricePerDay : Decimal
}

class TripGroup {
  +tripGroupId : String
  +maxParticipants : Integer
  +minParticipants : Integer
  +currentParticipants : Integer
}

class Booking {
  +bookingId : String
  +departureDate : Date
  +returnDate : Date
  +status : BookingStatus
  +totalPaidPrice : Decimal
  +currency : String
  +clientId : String
  +tripGroupId : String
  +rentalBikeId : String
  +tourId : String
}

class MaintenanceLog {
  +logId : String
  +bikeId : String
  +maintenanceDate : Date
  +cost : Decimal
  +description : String
}

' ==== Associations & multiplicities ====
Guide "1" -- "0..*" Stage  
TourPackage "1" -- "1..*" Stage
TourPackage "1" -- "1..*" Destination
TourPackage "1" -- "1..*" CyclingPath
TripGroup "1" -- "1" TourPackage
Client "1" -- "0..*" Booking
Booking "1" -- "1" TourPackage
Booking "0..1" -- "0..1" RentalBike


' CyclingPath start/end
CyclingPath "1" --> "1" Destination : from
CyclingPath "1" --> "1" Destination : to


' TourPackage composition of Stages
TourPackage "1" *-- "1..*" Stage

' TourPackage <-> Destination (main destinations)
TourPackage "0..*" -- "0..*" Destination

' RentalBike maintenance logs
RentalBike "1" -- "0..*" MaintenanceLog
@enduml